import { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
import { useAuth } from '../context/AuthContext'

const Home:NextPage= () => {
  const {currentUser} = useAuth()
  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login></Login>}
      {currentUser &&<UserDashboard></UserDashboard>}      
    </>
  )
}

export default Home
